spring:
  application:
    name: mall-user
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 139.9.48.23
    port: 5672
server:
  servlet:
    context-path: /shop
aliyun:
  oss:
    endpoint: xxx
    access-keyid: xxx
    access-keysecret: xxx
    bucketname: xxx

rabbit:
  delayed-exchange: delayed-exchange
  delayed-queue: delayed-queue
  delayed-routing-key: delayed.routingKey
  dead-letter-queue: dead-letter-queue
  dead-letter-exchange: dead-letter-exchange
  dead-letter-routing-key: dead.letter.routingKey
secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /configuration/ui
      - /webjars/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /sms/**
      - /user/register
      - /goods/list/**
      - /category/list
      - /oss/**
      - /alipay/notify
mybatis-plus:
  mapper-locations: classpath*:/**/mapper/xml/*.xml
