server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 651490
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  redis:
    host: 139.9.48.23
    port: 6379
    timeout: 300ms
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  appid: 2021000120617290
  app-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCbpsxLuMWLdHl4aLJSNTJR4M2NrBlz81GTL9FkepojeA1wbj/GQHN/RM8ig19816aERJJbkBhQx8KZTHBsI7FBOCPk56V0+8hUFuY3wYwZ93lAp5GOxB4r1FdoK9idJcuc9jP6vm14b2BWfICuzz1mZGVp0d2LqSVpA/hbYhXi6Pn3aUi9sOn8X7CKJ4pj9rOfuWaNdkDWuuklCKnBc0NrD0Gyo46izZp7dV+9XVIaiJs8DnPVolsyDj4xTpRB5RxqF1m7VjAbQCja3C+oQ/v9WTKd3NzLRj/mcbWtCpev8i8cPNrb7wYWMGIThx9KJwsoS3lZMRPD643y436nE6WrAgMBAAECggEAGNQUhoeky0f7EF/zAfYGXtUzNMQdE0fe3VGlXxfHepzt199eQOuLAOQi/mhiVPG5WCPwDLcBifEzc2ykCjvvTG3+G8dvtydqny8/7ejrxkCZkNyp9VIHVgp7HtzPotGilxkW1YqGv81UWrdld30LWEfvfV/CrUJ/+y5s8XbF8vni87N64cOlBgyzG4uNFJvb2rac/JrgaP4844KCEiqYdu/V21ZlkK5tQz5ojVj7mgTHlpctadxIlWp3i082j920v+rwpQPbzzgM3kpJe7ThStHXXMG8hyhbvTFKBbSYoKBOegjH82JpAnwjTIZNusxSsKpdJcMWdcJFYh3WhQ1xsQKBgQDYCVIe19T69hLqfG0hsITHlFwuxxTAlJ2haqfx+2vTXVO41X2PiHwBhZGIRf09RMixx9ewKkfsGokPqVhfemtEa3xgfB7FTVEpWsE/Dm/B6Y2Q5RdxTkbKeferWF77aL1l9uRyvoFX+cYoDn7VJQTkk3VCYuH7DcvenQDB/R/ezQKBgQC4ceAmGKKDk+XL+UnxlhXJNUbLQyCVE5IkFFA5GphX9/rK9BAuC3qkIp0TXtl4hspN+Ba7zsVKK8VRQsnWLeESMBRGSbvtZfXBMaplwLUaM3SYmPVipo6k2A2HGTKhZAfMXrcHlAplKcHmWgQrXGCoPzM5wC8ojx7fkVy4xd6mVwKBgBRfLKND7w2LTtVVzmSy5JJ9ZwPyOf6/BO5HxHaJIu3XiyGO4Dw8vpTWJ5cWIn84kURSeABgvE+DYRFdArxeKudUy3G9wpkQZWrk5/wuPFOo1nSnZcKFgx9syPIbbzl98v4+feRkGoZVQ15bn5Ix33g+f3w3HuAxuNvRKlUgrXSxAoGAT3GdHkuWFB5r6ENjug7vK08rQvmS2yMm2yt0smPmIl3JRAmDvpFrLa9LAMDl4qgMEzE8eYBCMgRQZQPjc8EnJHJZCT1RGJvGEoSV5GXwm2x2WBPp/afH4PC+QuZzjFhNk5VoOHdnUtN9lP5ItXSAnXc7VTCWH14l6h3uVhfEItkCgYAA5pBiLEgIrQ1OaXDBDN+Jj+ju9zArVhfPsRfm7F90oxfHF4qpayRum5dgLkYZkWIITEW4ALsReG0LEMC2DAMYXxM3tOkRvuWtvbtbkZpyul0DFvA0yvPa38c/d3Qg4UVU17AEA6ouxW9nwHWmwRH9F8DlSxK7BY1ExJsQHog66w==
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAolpXdJBB1GJNC3pHODQJgb0xagaF5o14HXTe+Vulk2uv1+xamLxdw/PgjMj7rJ4QhmNe3O0rnWvUszrj2GHx9RZQ3VzOZKAYa7W4bGEgd/sc2N7oo29VowE6nx41EkQeX3sEPvlQt7pPehL/9kD3xxD5r5HVlw4dyQ4K1CsNWKuVurJ/yAzCvIFN5+cGclXYH0pfubV/QdDMlCLalxgw6MuG0LPtJJG1NicKj7c99NommRpV0on/bna4Y5QLO/TI99IId/BPnEaHWrLxYTku4UobIK8PApDYZCHjadY3QWBoVNokjFq2gj4W/6KyNlmT1TpH/pKTrv2wWNC40gHOfQIDAQAB
  notify-url: http://139.9.48.23:8081/shop/alipay/notify
  gateway-url: https://openapi.alipaydev.com/gateway.do